# Generated by Django 5.0.6 on 2024-08-15 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BookModel',
        ),
    ]
